'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("student_bus_pass.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _0088181331020_Color_Sky_Blue_SW_60X602() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0088181331020_Color_Sky-Blue_SW_60X602", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _EXIT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EXIT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _NEXT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NEXT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Background_books_entry2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background books entry2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CLEA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLEA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CLEARB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLEARB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CLEARB1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLEARB1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property COLLE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COLLE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DELE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DELE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DELETE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DELETE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dsd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dsd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EXI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EXI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EXIT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EXIT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property INSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property INSERT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INSERT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logou() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logou", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NEX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NEX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PRI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SEA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SEA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SEARCH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SEARCH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SID() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SID", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property textures_wallpapers_simple_and_beautifull_wood_texture_backgrounds1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textures-wallpapers-simple-and-beautifull-wood-texture-backgrounds1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TIC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TIC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UPDATE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UPDATE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property USER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
